///////////////////////////////////////////////////////////
//  TiendaUsuario.cs
//  Implementation of the Class TiendaUsuario
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
namespace DeliveryOnline.Models {
	public class TiendaUsuario {

		private int nEstado;
		public DeliveryOnline.Models.Persona m_Persona;
		public DeliveryOnline.Models.Tienda m_Tienda;

		public TiendaUsuario(){

		}

		~TiendaUsuario(){

		}

		public int Estado{
			get{
				return nEstado;
			}
			set{
				nEstado = value;
			}
		}

	}//end TiendaUsuario

}//end namespace Models