///////////////////////////////////////////////////////////
//  TipoDocuVenta.cs
//  Implementation of the Class TipoDocuVenta
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:44
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
namespace DeliveryOnline.Models {
	public class TipoDocuVenta {

		private string cDescripcion;
		private int Id;
		public DeliveryOnline.Models.DocuVentaCorrelativo m_DocuVentaCorrelativo;

		public TipoDocuVenta(){

		}

		~TipoDocuVenta(){

		}

		public int CodigoId{
			get{
				return Id;
			}
			set{
				Id = value;
			}
		}

		public string Descripcion{
			get{
				return Descripcion;
			}
			set{
				Descripcion = value;
			}
		}

	}//end TipoDocuVenta

}//end namespace Models