///////////////////////////////////////////////////////////
//  Compra.cs
//  Implementation of the Class Compra
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique Incio Ch.
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
namespace DeliveryOnline.Models {
	public class Compra {

		private string cNroFactura;
		private DateTime dFechaCompra;
		private DateTime dFechaRegistro;
		private int Id;
		private int nEstado;
		public DeliveryOnline.Models.DetalleCompra m_DetalleCompra;
		public DeliveryOnline.Models.Tienda m_Tienda;

		public Compra(){

		}

		~Compra(){

		}

		public int CodigoId{
			get{
				return Id;
			}
			set{
				Id = value;
			}
		}

		public List<DetalleCompra> detalleCompra{
			get{
				return detalleCompra;
			}
			set{
				detalleCompra = value;
			}
		}

		public int Estado{
			get{
				return nEstado;
			}
			set{
				nEstado = value;
			}
		}

		public DateTime FechaCompra{
			get{
				return dFechaCompra;
			}
			set{
				dFechaCompra = value;
			}
		}

		public DateTime FechaRegistro{
			get{
				return dFechaRegistro;
			}
			set{
				dFechaRegistro = value;
			}
		}

		public string NroFactura{
			get{
				return cNroFactura;
			}
			set{
				cNroFactura = value;
			}
		}

	}//end Compra

}//end namespace Models