///////////////////////////////////////////////////////////
//  Insumo.cs
//  Implementation of the Class Insumo
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace DeliveryOnline.Models {
	public class Insumo {

		private string cDescripcion;
		private int Id;

		public Insumo(){

		}

		~Insumo(){

		}

		public int CodigoId{
			get{
				return Id;
			}
			set{
				Id = value;
			}
		}

		public string Descripcion{
			get{
				return cDescripcion;
			}
			set{
				cDescripcion = value;
			}
		}

	}//end Insumo

}//end namespace Models