///////////////////////////////////////////////////////////
//  Producto.cs
//  Implementation of the Class Producto
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique Incio Ch
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace DeliveryOnline.Models {
	public class Producto {

		private string cDescripcion;
		private string cImagen;
		private int Id;
        
		//public DeliveryOnline.Models.TiendaProducto m_TiendaProducto;
		public DeliveryOnline.Models.TiposMenu m_TiposMenu;

        [ForeignKey("Tienda")]
        public int TiendaId { get; set; }

        public virtual Tienda Tienda { get; set; }

		public Producto(){

		}

		~Producto(){

		}

        [Key()]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CodigoId{
			get{
				return Id;
			}
			set{
				Id = value;
			}
		}

		public string Descripcion{
			get{
				return cDescripcion;
			}
			set{
				cDescripcion = value;
			}
		}

		public string Imagen{
			get{
				return cImagen;
			}
			set{
				cImagen = value;
			}
		}

	}//end Producto

}//end namespace Models