///////////////////////////////////////////////////////////
//  TiposMenu.cs
//  Implementation of the Class TiposMenu
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:44
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace DeliveryOnline.Models {
	public class TiposMenu {

		private string cDescripcion;
		private int Id;

		public TiposMenu(){

		}

		~TiposMenu(){

		}

		public int CodigoId{
			get{
				return Id;
			}
			set{
				Id = value;
			}
		}

		public string Descripcion{
			get{
				return cDescripcion;
			}
			set{
				cDescripcion = value;
			}
		}

	}//end TiposMenu

}//end namespace Models