///////////////////////////////////////////////////////////
//  TipoCliente.cs
//  Implementation of the Class TipoCliente
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Microsoft.AspNet.Identity.EntityFramework;

namespace DeliveryOnline.Models {
	public class TipoCliente : IdentityRole{

	}//end TipoCliente

}//end namespace Models