///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Persona
//  Generated by Enterprise Architect
//  Created on:      30-Set.-2017 12:37:43
//  Original author: Enrique Incio Ch
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DeliveryOnline.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;

namespace DeliveryOnline.Models {
	public class Persona : IdentityUser {

		private string cApellidos;
		private string cDireccion;
		private string cNombre;

        public DeliveryOnline.Models.TipoCliente m_TipoCliente;
		//public DeliveryOnline.Models.TiendaUsuario m_TiendaUsuario;
        public virtual ICollection<Tienda> Tiendas { get; set; }


		~Persona(){

		}

		public string Apellidos{
			get{
				return cApellidos;
			}
			set{
				cApellidos = value;
			}
		}

        public string Direccion{
			get{
				return cDireccion;
			}
			set{
				cDireccion = value;
			}
		}

		
		public string Nombre{
			get{
				return cNombre;
			}
			set{
				cNombre = value;
			}
		}

        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<Persona> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }

    }//end Persona

}//end namespace Models