//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCV.UIClient.UCV.Reserva {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UCV.Reserva.IReservaService")]
    public interface IReservaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/GetReservas", ReplyAction="http://tempuri.org/IReservaService/GetReservasResponse")]
        System.Collections.Generic.List<UCV.Comun.Modelos.Reserva> GetReservas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/GetReservas", ReplyAction="http://tempuri.org/IReservaService/GetReservasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UCV.Comun.Modelos.Reserva>> GetReservasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/GetReservasById", ReplyAction="http://tempuri.org/IReservaService/GetReservasByIdResponse")]
        System.Collections.Generic.List<UCV.Comun.Modelos.Reserva> GetReservasById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/GetReservasById", ReplyAction="http://tempuri.org/IReservaService/GetReservasByIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UCV.Comun.Modelos.Reserva>> GetReservasByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/GetReservasByIdFecha", ReplyAction="http://tempuri.org/IReservaService/GetReservasByIdFechaResponse")]
        System.Collections.Generic.List<UCV.Comun.Modelos.Reserva> GetReservasByIdFecha(string id, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/GetReservasByIdFecha", ReplyAction="http://tempuri.org/IReservaService/GetReservasByIdFechaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UCV.Comun.Modelos.Reserva>> GetReservasByIdFechaAsync(string id, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/GetReservaByIdFechaRuta", ReplyAction="http://tempuri.org/IReservaService/GetReservaByIdFechaRutaResponse")]
        System.Collections.Generic.List<UCV.Comun.Modelos.Reserva> GetReservaByIdFechaRuta(string id, System.DateTime fecha, UCV.Comun.Modelos.Ruta ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/GetReservaByIdFechaRuta", ReplyAction="http://tempuri.org/IReservaService/GetReservaByIdFechaRutaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UCV.Comun.Modelos.Reserva>> GetReservaByIdFechaRutaAsync(string id, System.DateTime fecha, UCV.Comun.Modelos.Ruta ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/SaveReserva", ReplyAction="http://tempuri.org/IReservaService/SaveReservaResponse")]
        void SaveReserva(UCV.Comun.Modelos.Reserva reserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/SaveReserva", ReplyAction="http://tempuri.org/IReservaService/SaveReservaResponse")]
        System.Threading.Tasks.Task SaveReservaAsync(UCV.Comun.Modelos.Reserva reserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/UpdateReserva", ReplyAction="http://tempuri.org/IReservaService/UpdateReservaResponse")]
        void UpdateReserva(UCV.Comun.Modelos.Reserva reserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/UpdateReserva", ReplyAction="http://tempuri.org/IReservaService/UpdateReservaResponse")]
        System.Threading.Tasks.Task UpdateReservaAsync(UCV.Comun.Modelos.Reserva reserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/DeleteReserva", ReplyAction="http://tempuri.org/IReservaService/DeleteReservaResponse")]
        void DeleteReserva(UCV.Comun.Modelos.Reserva reserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/DeleteReserva", ReplyAction="http://tempuri.org/IReservaService/DeleteReservaResponse")]
        System.Threading.Tasks.Task DeleteReservaAsync(UCV.Comun.Modelos.Reserva reserva);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservaServiceChannel : UCV.UIClient.UCV.Reserva.IReservaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservaServiceClient : System.ServiceModel.ClientBase<UCV.UIClient.UCV.Reserva.IReservaService>, UCV.UIClient.UCV.Reserva.IReservaService {
        
        public ReservaServiceClient() {
        }
        
        public ReservaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<UCV.Comun.Modelos.Reserva> GetReservas() {
            return base.Channel.GetReservas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UCV.Comun.Modelos.Reserva>> GetReservasAsync() {
            return base.Channel.GetReservasAsync();
        }
        
        public System.Collections.Generic.List<UCV.Comun.Modelos.Reserva> GetReservasById(string id) {
            return base.Channel.GetReservasById(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UCV.Comun.Modelos.Reserva>> GetReservasByIdAsync(string id) {
            return base.Channel.GetReservasByIdAsync(id);
        }
        
        public System.Collections.Generic.List<UCV.Comun.Modelos.Reserva> GetReservasByIdFecha(string id, System.DateTime fecha) {
            return base.Channel.GetReservasByIdFecha(id, fecha);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UCV.Comun.Modelos.Reserva>> GetReservasByIdFechaAsync(string id, System.DateTime fecha) {
            return base.Channel.GetReservasByIdFechaAsync(id, fecha);
        }
        
        public System.Collections.Generic.List<UCV.Comun.Modelos.Reserva> GetReservaByIdFechaRuta(string id, System.DateTime fecha, UCV.Comun.Modelos.Ruta ruta) {
            return base.Channel.GetReservaByIdFechaRuta(id, fecha, ruta);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UCV.Comun.Modelos.Reserva>> GetReservaByIdFechaRutaAsync(string id, System.DateTime fecha, UCV.Comun.Modelos.Ruta ruta) {
            return base.Channel.GetReservaByIdFechaRutaAsync(id, fecha, ruta);
        }
        
        public void SaveReserva(UCV.Comun.Modelos.Reserva reserva) {
            base.Channel.SaveReserva(reserva);
        }
        
        public System.Threading.Tasks.Task SaveReservaAsync(UCV.Comun.Modelos.Reserva reserva) {
            return base.Channel.SaveReservaAsync(reserva);
        }
        
        public void UpdateReserva(UCV.Comun.Modelos.Reserva reserva) {
            base.Channel.UpdateReserva(reserva);
        }
        
        public System.Threading.Tasks.Task UpdateReservaAsync(UCV.Comun.Modelos.Reserva reserva) {
            return base.Channel.UpdateReservaAsync(reserva);
        }
        
        public void DeleteReserva(UCV.Comun.Modelos.Reserva reserva) {
            base.Channel.DeleteReserva(reserva);
        }
        
        public System.Threading.Tasks.Task DeleteReservaAsync(UCV.Comun.Modelos.Reserva reserva) {
            return base.Channel.DeleteReservaAsync(reserva);
        }
    }
}
